# Generated by Django 6.0.4 on 2026-04-25 04:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('17f25f8b-8cfd-49ac-a412-7f61337171b1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
