# Generated by Django 6.0.4 on 2026-04-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recipe_app', '0006_chat_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='raw_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
