# Generated by Django 6.0.4 on 2026-05-01 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recipe_app', '0008_chatmessage_media_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='media_json',
        ),
    ]
