# Generated by Django 6.0.4 on 2026-05-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recipe_app', '0009_remove_chatmessage_media_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodImageCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('query', models.CharField(max_length=255)),
                ('images_json', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
