# Generated by Django 6.0.4 on 2026-05-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recipe_app', '0010_food_image_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
    ]
