# Generated by Django 6.0.4 on 2026-04-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notif_recipe_suggestions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notif_tips_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notif_weekly_digest',
            field=models.BooleanField(default=False),
        ),
    ]
