"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import dj_database_url

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-wflf&#zqi-6_^0j4*gvasjs)m4=-z63hlkx122s2-6lrb7pl$!",
)

DEBUG = os.environ.get("DEBUG", "True").lower() == "true"

_allowed = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1")
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(",") if h.strip()]
ALLOWED_HOSTS += [".vercel.app"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ai_recipe_app.apps.AiRecipeAppConfig',
    'authentication.apps.AuthenticationConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'context_processors.context_processors',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_db_url = os.environ.get("DATABASE_URL")
if _db_url:
    DATABASES = {"default": dj_database_url.parse(_db_url, conn_max_age=600)}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles_collected'
STATICFILES_DIRS = [BASE_DIR / 'static']

STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}

MISTRAL_API_KEY = os.environ["MISTRAL_API_KEY"]

GOOGLE_CLIENT_ID     = os.environ.get("GOOGLE_CLIENT_ID", "")
GOOGLE_CLIENT_SECRET = os.environ.get("GOOGLE_CLIENT_SECRET", "")
GOOGLE_REDIRECT_URI  = os.environ.get("GOOGLE_REDIRECT_URI", "http://localhost:8000/auth/google/callback/")

# Apple Sign In — set these in .env
# APPLE_PRIVATE_KEY is the full contents of the .p8 file (multi-line, with -----BEGIN PRIVATE KEY-----)
APPLE_CLIENT_ID   = os.environ.get("APPLE_CLIENT_ID", "")    # Service ID (e.g. com.example.app.signin)
APPLE_TEAM_ID     = os.environ.get("APPLE_TEAM_ID", "")      # 10-char Team ID from Apple Developer
APPLE_KEY_ID      = os.environ.get("APPLE_KEY_ID", "")       # Key ID from the .p8 key
APPLE_PRIVATE_KEY = os.environ.get("APPLE_PRIVATE_KEY", "")  # .p8 file contents (newlines as \n in .env)
APPLE_REDIRECT_URI = os.environ.get("APPLE_REDIRECT_URI", "http://localhost:8000/auth/apple/callback/")
MISTRAL_MODEL = os.environ["MISTRAL_MODEL"]

AZURE_OPENAI_API_KEY= os.environ["AZURE_OPENAI_API_KEY"]
AZURE_OPENAI_ENDPOINT=os.environ["AZURE_OPENAI_ENDPOINT"]
AZURE_DEPLOYMENT_NAME=os.environ["AZURE_DEPLOYMENT_NAME"]

# Email — defaults to console backend so OTP codes are printed to the terminal
# during development. Set EMAIL_BACKEND and SMTP_* vars in .env for production.
EMAIL_BACKEND   = os.environ.get("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply@recipechef.app")
EMAIL_HOST      = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT      = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_USE_TLS   = os.environ.get("EMAIL_USE_TLS", "true").lower() == "true"
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")

USE_I18N = True

# Use the custom user model from the local `auth` app
AUTH_USER_MODEL = 'authentication.User'

# Use the Email+OTP authentication backend by default. Keep Django's
# ModelBackend in the back so permissions and admin login continue to work
# if you also want to support password authentication.
AUTHENTICATION_BACKENDS = [
    'authentication.backends.EmailOTPBackend',
    'django.contrib.auth.backends.ModelBackend',
]

TASKS = {"default": {"BACKEND": "django.tasks.backends.immediate.ImmediateBackend"}}

LOGIN_URL = "/chat/"
LOGIN_REDIRECT_URL = "/chat/"
LOGOUT_REDIRECT_URL = "/chat/"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
